### ISSUE TITLE
How to install more current versions on Ubuntu 16.04

### ISSUE THREAD

**Issue by jurgenhaas** [liske/needrestart#107]
This might be too obvious and I'm sorry if that's documented somewhere already, I just couldn't find it and hence need to ask.

On Ubuntu 16.04 I can only find version 2.6 packages and even launchpad.net has nothing more current.

So, what's the recommended way to install 2.9 or even 3.0? Do I have to self-compile? If so, I'd much appreciate some guidelines or instructions.

**Comment by liske** [comment]
I have no recommendation howto install needrestart on Ubuntu. Sadly Ubuntu has no maintainer for needrestart and most Ubuntu releases are shipping needrestart packages with well known bugs (they have been picked from Debian testing but do not care about further bug fixes). So please address your question to the Ubuntu guys or community.

**Unofficial** hint: you might try to just grab a more recent .deb from Debian and install it manually using *dpkg* - since needrestart does not contain any binaries this should work - use at your own risk ;-)

**Comment by jurgenhaas** [comment]
Thanks @liske for your unofficial hint. Any link to a trusted source for the latest deb packages though?
