### ISSUE TITLE
Tries to restart a text file

### ISSUE THREAD

**Issue by duck-rh** [liske/needrestart#116]
Quack,

Since CentOS 7.5, developers have decided to remind people to use systemd and added `/etc/init.d/README`. This result into:
```
WARNING: /etc/init.d/README has no LSB tags!
```
and later:
```
Failed to restart README.service: Unit not found.
```

From what I can see, there is also a `/etc/init.d/functions` file but not sure how it is ignored (not in the blacklist_rc).

We have a README file in Debian too but never had this problem.

Seems non-executable files in this directory should be ignored (at least on CentOS and Debian is would work), that might be a solution.

\_o<

**Comment by liske** [comment]
Hi,

if needrestart is unable to find a service unit to restart a daemon it uses a heuristic to detect Sys-V init scripts. Could you please provide the debugging output of `needrestart -v -r l`?

**Comment by duck-rh** [comment]
Here it is:

[needrestart_issue_116.log](https://github.com/liske/needrestart/files/2022970/needrestart_issue_116.log)

**Comment by liske** [comment]
Thanks!

This looks wired:

```
[main] #1 exe => /usr/lib/systemd/systemd
[main] #1 unexpected cgroup '/'
[main] trying systemctl status
Failed to get unit for PID 1: PID 1 does not belong to any loaded unit.
[main] #1 running /etc/needrestart/hook.d/10-dpkg
[main] #1 running /etc/needrestart/hook.d/20-rpm
[main] #1 package: systemd-219-57.el7.x86_64
WARNING: /etc/init.d/README has no LSB tags!
[main] no LSB headers found at README
```

I would expect `systemctl status 1` to report that it belongs to `init.scope` (so it does on Debian stretch). The README is detected as init script since cgroup and systemctl detection has failed and it using the README since it looks like a init script. Fixing the README stuff is easy but it looks like another problem (or a problem on the host/CentOS's systemd?).
