### ISSUE TITLE
CentOS8/RHEL8 RPM

### ISSUE THREAD

**Issue by guruguruguru** [liske/needrestart#187]
Hi,

are there any plans to release needrestart as RPM for RHEL8/CentOS8?
The package is missing in the EPEL Repo where it resided in CentOS7

Thanks,
Dennis

**Comment by liske** [comment]
Unfortunately I'm not able to maintain packages for CentOS or RHEL.

**Comment by guruguruguru** [comment]
@duck-rh I have read at least one bug in redhats bugtracker where it seems you are on this topic?

**Comment by duck-rh** [comment]
@guruguruguru you're right Sir.

My work came too late to be in RHEL 8 but I planned to make it available on EPEL 8 after some testing and forgot to make it happen, sorry. The tests have been done though so it should be a matter for getting the branch and waiting it goes out of EPEL-testing.

And I need to update EPEL 7 too /o\.

**Comment by guruguruguru** [comment]
@duck-rh ```yum install /tmp/needrestart-3.5-2.el8.noarch.rpm 
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 0:03:49 ago on Fri Jul  3 13:40:24 2020.
Error: 
 Problem: conflicting requests
  - nothing provides iucode-tool needed by needrestart-3.5-2.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)```

**Comment by duck-rh** [comment]
@guruguruguru the package in EPEL7 has been present for some time but was not the latest version because I forgot to update it, but it works fine. The new version is also in testing.

As for EPEL8, I opened a BR on iucode-tool some time ago but no reply yet:
  https://bugzilla.redhat.com/show_bug.cgi?id=1814104
I pinged on the ticket in hope the maintainer would wakeup.

This package just need a rebuild with any change. You can find it in our repository:
  https://copr.fedorainfracloud.org/coprs/duck/osas-infra-team-rpm-repo/

For bugs on official packages, it would be better to use bugzilla.redhat.com, nevertheless it's also good to keep people up-to-date about the progress here. But it's ok for this one, no need to open another one.

**Comment by duck-rh** [comment]
needrestart is up-to-date on EPEL 7 and 8 now.

I got contact with the iucode-tool maintainer and he requested the branch to be able to push the package to EPEL 8 but that's still going to take some time. I'll update this ticket when I have more info.

**Comment by guruguruguru** [comment]
@duck-rh thank you so much for your efforts!

**Comment by duck-rh** [comment]
It should be there by Friday: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-4352ecf8a6

**Comment by duck-rh** [comment]
Here it is. Unless someone has a problem to report about the packaging, I think we can close this issue.

**Comment by guruguruguru** [comment]
@duck-rh yes, thank you!

**Comment by liske** [comment]
Thanks @duck-rh - I close this issue since it seems to be fixed.
