### ISSUE TITLE
Deactivate temporally needrestart during a system upgrade

### ISSUE THREAD

**Issue by GMLudo** [liske/needrestart#71]
Hi,

Thanks a lot for needrestart, we install this package by default on all Debian servers.
However, we have a small question: We use also Ansible to upgrade and deploy new software on the servers.
Time to time, we would avoid to restart all daemons just after the upgrade and we want to launch needrestart after the end of playbook.
Is it possible to pass a parameter to disable temporally needrestart via an environment variable for example ?
I see nothing like that inside the hooks for apt and dpkg.

Thanks for your answer.

Regards.

**Comment by GMLudo** [comment]
Gentle ping ;-)

**Comment by liske** [comment]
It is currently not possible to override *needrestart*'s behavior (w/o changing config files). You could prevent *needrestart* to restart any services by using Debian's policy layer (`invoke-rc.d`) - but that would also block any service (re)starts from the install/upgrade scripts.

A way to implement such a feature might be to add a checking for an environment variable within `/usr/lib/needrestart/apt-pinvoke` to prevent the starting of *needrestart* (this script is executed by `/etc/apt/apt.conf.d/99needrestart`). To check if `needrestart` is required to run due to apt operations we could check for the presence of the `/run/needrestart/unpacked` file to trigger an *Ansible* handler.

**Comment by GMLudo** [comment]
@liske Thank you a lot, it confirms what we are thinking to do.
If we have some interesting to show, we will do a PR.

Regards.

**Comment by ge-fa** [comment]
@GMLudo A MR implementing this feature would be highly appreciated!

**Comment by Farom** [comment]
This feature would be really helpful. I would write it in the described way, but my last perl experience was 15 years ago ... so better not.

**Comment by pmorch** [comment]
We've also come up with a different method: Put this in `/etc/needrestart/conf.d/disable.conf`:

```
# Restart services (l)ist only, (i)nteractive or (a)utomatically. 
$nrconf{restart} = 'l'; 
# Disable hints on pending kernel upgrades. 
$nrconf{kernelhints} = 0; 
```
Now it doesn't interrupt `apt` with interactive queries. Does anybody see holes in this or some way this becomes interactive anyway?

Another alternative to consider is to use `dpkg-divert` to move `/etc/apt/apt.conf.d/99needrestart` somewhere else.

I don't think just modifying `/usr/lib/needrestart/apt-pinvoke` or `/etc/apt/apt.conf.d/99needrestart` without `dpkg-divert` is a good idea, because later, when the `needrestart` package itself is upgraded, any modifications will be overwritten with the contents of the new upstream files and you'll be back to the original behaviour.

Personally, I'd like to see some way to avoid `needrestart` changing the interactivity of `apt` though. E.g. obey the `DEBIAN_PRIORITY` environment variable and not do anything if it equals `critical`.

**Comment by pmorch** [comment]
What we actually ended up doing was:
```
mkdir /etc/apt/disabled.apt.conf.d/
dpkg-divert --divert /etc/apt/disabled.apt.conf.d/99needrestart  --rename /etc/apt/apt.conf.d/99needrestart
```

**Comment by liske** [comment]
You now can disable to *apt-get* hook which runs *needrestart* if a package was installed or updated by setting the environment variable __NEEDRESTART_SUSPEND__ to a non-empty value. Should work with _ansible_'s `environment:` keyword.

**Comment by Sieboldianus** [comment]
You can also add `NEEDRESTART_MODE: automatically`, see [#35497](https://github.com/ansible/ansible/issues/35497)

**Comment by jonathanMelly** [comment]
> You can also add `NEEDRESTART_MODE: automatically`, see [#35497](https://github.com/ansible/ansible/issues/35497)

this gives me ERROR: Unknown restart option 'automatically'!

But "NEEDRESTART_SUSPEND=y" works
